FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y

RUN apt install nginx -y

COPY lb /etc/nginx/sites-available/default

ENTRYPOINT ["nginx", "-g", "daemon off;"]
