pipeline {
    agent any

    stages {
        stage ('Build image') {
            steps {
                sh '''
                docker build -f dockerfiles/load_balancer/dockerfile -t wantsomeproject/load_balancer:0.0.1 .
                '''
            }
        }
        stage ('Push to DockerHub') {
            steps {
                sh '''
                echo wantsomeproject | docker login -u wantsomeproject --password-stdin
                docker push wantsomeproject/load_balancer:0.0.1
                ''' 
            }
        }
        stage ('Deploy') {
            steps {
                 sh '''
                 ssh -o StrictHostKeyChecking=no vagrant@192.168.56.20 '
                 echo wantsomeproject | sudo docker login -u wantsomeproject --password-stdin
                 sudo docker pull wantsomeproject/load_balancer:0.0.1
                 sudo docker run -d --name load_balancer -p 80:80 --network wantsome wantsomeproject/load_balancer:0.0.1
                 '
                 '''
            }
        }
    }
}
